name: Lundy Way
favicon: null
layout_spectrum: 1
typography_spectrum: 0.35486
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#ffffff'
    - '#777777'
    - '#414141'
    - '#84b878'
  brandStrength: 0.375
  lightness: 0.3125
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
