name: Lundy Way
favicon: null
layout_spectrum: 0.7238277327269316
typography_spectrum: 0.72548
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#030200'
    - '#0a5d85'
    - '#9ab4c3'
    - '#d8e9f0'
    - '#504540'
  brandStrength: 0.6835464695468545
  lightness: 0.3398650416638702
  saturation: 0.4342645248398185
  rhythmicContrast: 0.14278812427073717
purpose: []
