name: Lundy Way
favicon: null
layout_spectrum: 1
typography_spectrum: 0.26279
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#f5bb8d'
    - '#a41437'
    - '#474e54'
    - '#dc6566'
  brandStrength: 0.3125
  lightness: 0.3125
  saturation: 0.3125
  rhythmicContrast: 0.25
purpose: []
