name: Lundy Way
favicon: null
layout_spectrum: 1
typography_spectrum: 0.35486
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#ffffff'
    - '#777777'
    - '#414141'
    - '#84b878'
  brandStrength: 0.6835464695468545
  lightness: 0.3398650416638702
  saturation: 0.4342645248398185
  rhythmicContrast: 0.14278812427073717
purpose: []
