name: Lundy Way
favicon: null
layout_spectrum: 1
typography_spectrum: 0.35486
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#000000'
    - '#ababab'
    - '#303030'
    - '#2963ba'
  brandStrength: 0.3125
  lightness: 0.3125
  saturation: 0.3125
  rhythmicContrast: 0.25
purpose: []
